language: node_js
node_js:
  - "11.6.0"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
after_script:
  - git config user.name "athena"
  - git config user.email "athena0304@gmail.com"
  - git add .
  - git commit -m "auto build"
  - git pull
  - git push "https://${GH_TOKEN}@${GH_REF}" master:master
branchs:
  only:
  - master

env:
 global:
   - GH_REF: github.com/athena0304/gsteps-mobile.git